# Copyright (c) 2026, InfraBeat and contributors
# For license information, please see license.txt
"""
Ping Check controller.

Lifecycle hooks and business logic for the Ping Check DocType.
Generated by infrabeat-doctype skill on 2026-05-05.
"""

import frappe
from frappe import _
from frappe.model.document import Document


class PingCheck(Document):
    """Controller for the Ping Check DocType."""

    # =========================================================================
    # Lifecycle hooks
    # =========================================================================

    def validate(self) -> None:
        """Run before save (insert and update). Raise ValidationError to block."""
        self._normalize_fields()
        self._validate_business_rules()

    def before_save(self) -> None:
        """Run after validate, before DB write. Use for derived fields."""
        pass

    def on_update(self) -> None:
        """Run after DB write on insert and update."""
        pass

    def on_submit(self) -> None:
        """Run after submission. Only fires if is_submittable=1."""
        pass

    def on_cancel(self) -> None:
        """Run on cancellation. Only fires if is_submittable=1."""
        pass

    def on_trash(self) -> None:
        """Run before deletion. Raise to block deletion."""
        pass

    # =========================================================================
    # Helpers
    # =========================================================================

    def _normalize_fields(self) -> None:
        """Trim strings, lowercase emails, etc. Idempotent."""
        pass

    def _validate_business_rules(self) -> None:
        """Project-specific validations. Override or extend per business need."""
        pass


# =============================================================================
# Whitelisted methods (AJAX-callable from client scripts)
# =============================================================================

@frappe.whitelist()
def get_summary(name: str) -> dict:
    """Return a dictionary summary of a Ping Check record.

    Permissions are checked by Frappe before this runs.
    """
    if not name:
        frappe.throw(_("Record name is required"))

    doc = frappe.get_doc("Ping Check", name)
    return {
        "name": doc.name,
        "modified": doc.modified,
        "owner": doc.owner,
    }
