// Copyright (c) 2026, InfraBeat and contributors
// For license information, please see license.txt
//
// Ping Check client script.
// Generated by infrabeat-doctype skill on 2026-05-05.

frappe.ui.form.on("Ping Check", {
    // =========================================================================
    // Lifecycle events
    // =========================================================================

    refresh: (frm) => {
        // Runs every time the form refreshes (open, save, navigate).
        // Use for dynamic buttons, conditional UI, indicators.
    },

    onload: (frm) => {
        // Runs once when form first loads.
        // Use for setting up filters on link fields.
    },

    validate: (frm) => {
        // Client-side validation. Returns false to block save.
    },

    before_save: (frm) => {
        // Runs after client validate, before server hit.
    },

    after_save: (frm) => {
        // Runs after server confirms save. Good place for show_alert.
        frappe.show_alert({
            message: __("Ping Check saved"),
            indicator: "green"
        }, 3);
    },

    // =========================================================================
    // Field-level events (uncomment and customize as needed)
    // =========================================================================

    // message: (frm) => {
    //     // Fires when this field changes.
    // },
});

// =========================================================================
// Helpers (module-scope, callable from form events)
// =========================================================================

const _fetchSummary = (frm) => {
    // Example: call the whitelisted server method get_summary.
    if (!frm.doc.name || frm.is_new()) return;

    frappe.call({
        method: "custom_erp.doctype.ping_check.ping_check.get_summary",
        args: { name: frm.doc.name },
        callback: (r) => {
            if (r.message) {
                console.log("Summary:", r.message);
            }
        }
    });
};
