# Copyright (c) 2026, InfraBeat and contributors
# See license.txt
"""
Tests for Ping Check DocType.

Run with:
    bench --site erp.local run-tests --doctype "Ping Check"

Generated by infrabeat-doctype skill on 2026-05-05.
"""

import frappe
from frappe.tests.utils import FrappeTestCase


class TestPingCheck(FrappeTestCase):
    """Test suite for Ping Check."""

    @classmethod
    def setUpClass(cls) -> None:
        """Run once before all tests in this class."""
        super().setUpClass()
        # Insert any shared fixtures here.

    def setUp(self) -> None:
        """Run before each test. Roll back happens automatically after."""
        pass

    def tearDown(self) -> None:
        """Run after each test. FrappeTestCase rolls back DB by default."""
        pass

    # =========================================================================
    # Happy path
    # =========================================================================

    def test_create_minimal_record(self):
        """Creating a Ping Check with required fields succeeds."""
        doc = frappe.get_doc({
            "doctype": "Ping Check",
            "message": "_Test Ping Check 001",
        })
        doc.insert(ignore_permissions=False)

        self.assertTrue(doc.name)
        self.assertEqual(doc.doctype, "Ping Check")
        self.assertEqual(doc.message, "_Test Ping Check 001")

    # =========================================================================
    # Validation
    # =========================================================================

    def test_missing_required_field_raises(self):
        """Saving without the required message field raises ValidationError."""
        doc = frappe.get_doc({
            "doctype": "Ping Check",
            # Intentionally omit "message".
        })
        with self.assertRaises(frappe.ValidationError):
            doc.insert(ignore_permissions=False)

    # =========================================================================
    # Business rules (extend as project grows)
    # =========================================================================

    # def test_<rule_name>(self):
    #     """Document the rule, then assert it."""
    #     pass
