---
all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/infrabeat_ed25519
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    dev:
      ansible_host: 10.1.0.184
      ansible_user: erpadmin
      bench_user: frappe
      bench_path: /home/frappe/frappe-bench
      site_name: erp.local
      branch_name: dev
      bench_mode: dev
      node_version: "18"
      frappe_branch: version-15
      erpnext_branch: version-15
