# Copyright (c) 2026, PrasadInfraBeat and contributors
# For license information, please see license.txt

# import frappe
from frappe.model.document import Document


class CustomerVisit(Document):
    """Auto-generated by Claude AI."""
    pass
